// Stage 5 — Publish: create a fresh GitHub repo under the authenticated user and
// push the generated site as a single commit via the Git Data API.

import fs from "node:fs";
import path from "node:path";

import { Octokit } from "@octokit/rest";

import { jobWorkspace } from "../config";

const EXCLUDE_DIRS = new Set([
  "node_modules",
  ".next",
  ".git",
  ".studio",
  ".claude", // design skills were only needed by the generating agent
  "brand", // internal working assets (brief.json, source screenshots)
]);

type PublishResult = { repoUrl: string; repoFullName: string; owner: string; repo: string };

function walk(dir: string, base = dir): string[] {
  const out: string[] = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.isDirectory()) {
      if (EXCLUDE_DIRS.has(entry.name)) continue;
      out.push(...walk(path.join(dir, entry.name), base));
    } else if (entry.isFile()) {
      out.push(path.relative(base, path.join(dir, entry.name)));
    }
  }
  return out;
}

export async function publish(
  jobId: string,
  token: string,
  slug: string,
  privateRepo: boolean,
  onLog: (message: string) => void,
): Promise<PublishResult> {
  const workspace = jobWorkspace(jobId);
  const octokit = new Octokit({ auth: token });

  const { data: me } = await octokit.users.getAuthenticated();
  const owner = me.login;
  onLog(`Angemeldet als ${owner}. Erstelle Repository "${slug}" …`);

  const { data: repo } = await octokit.repos.createForAuthenticatedUser({
    name: slug,
    private: privateRepo,
    auto_init: false,
    description: "Von Scope Studio generierte Premium-Website.",
  });
  const repoName = repo.name;

  const files = walk(workspace);
  onLog(`Lade ${files.length} Dateien hoch …`);

  const tree: {
    path: string;
    mode: "100644";
    type: "blob";
    sha: string;
  }[] = [];

  for (const rel of files) {
    const abs = path.join(workspace, rel);
    const content = fs.readFileSync(abs).toString("base64");
    const { data: blob } = await octokit.git.createBlob({
      owner,
      repo: repoName,
      content,
      encoding: "base64",
    });
    tree.push({ path: rel.split(path.sep).join("/"), mode: "100644", type: "blob", sha: blob.sha });
  }

  const { data: createdTree } = await octokit.git.createTree({
    owner,
    repo: repoName,
    tree,
  });
  const { data: commit } = await octokit.git.createCommit({
    owner,
    repo: repoName,
    message: "Initial premium website — generated by Scope Studio",
    tree: createdTree.sha,
    parents: [],
  });
  await octokit.git.createRef({
    owner,
    repo: repoName,
    ref: "refs/heads/main",
    sha: commit.sha,
  });

  onLog(`Repository bereit: ${repo.html_url}`);
  return { repoUrl: repo.html_url, repoFullName: repo.full_name, owner, repo: repoName };
}
